//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magaz.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mmas
    {
        public int ID { get; set; }
        public string Name_Brend { get; set; }
        public string Viscosity { get; set; }
        public string Country { get; set; }
        public string Price { get; set; }
    }
}
