//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magaz.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AvtozaptEntities1 : DbContext
    {
        public AvtozaptEntities1()
            : base("name=AvtozaptEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Akk> Akk { get; set; }
        public virtual DbSet<Din> Din { get; set; }
        public virtual DbSet<Mag> Mag { get; set; }
        public virtual DbSet<Sab> Sab { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Zy> Zy { get; set; }
        public virtual DbSet<Antf> Antf { get; set; }
        public virtual DbSet<Mmas> Mmas { get; set; }
        public virtual DbSet<Navig> Navig { get; set; }
        public virtual DbSet<Scys> Scys { get; set; }
        public virtual DbSet<Ssal> Ssal { get; set; }
        public virtual DbSet<Tmas> Tmas { get; set; }
    }
}
